### ISSUE TITLE
Bug: Failed to find the PHP version for c:/Program Files/php-8.2.18-Win32-vs16-x64

### ISSUE THREAD

**Issue by maxmhoff** [yCodeTech/valet-windows#11]
### Description

When trying to install I get this error: `Failed to find the PHP version for c:/Program Files/php-8.2.18-Win32-vs16-x64` at the 20% mark. I've installed cretueusebiu's version prior to this without any issues, and I'm fairly certain I removed everything before installing this. Manually adding the php version with `valet php:add "c:/Program Files/php-8.2.18-Win32-vs16-x64"` didn't address the issue

### Steps To Reproduce

1. Download php 8.2.18-Win32-vs16-x64 from https://windows.php.net/
2. Add path to env variables
3. Install composer
4. Require yCodeTech/valet-windows
5. Valet install

### Diagnosis

`valet diagnose`
returns
`Command "diagnose" is not defined`

**Comment by hemant-kr-meena** [comment]
I think this is due to the old config file. When we try to remove the old version it removes the package. but doesn't remove the config file.

This file is responsible for storing all valet settings like php path and other things.

you should also need to remove these files also.

**Comment by hemant-kr-meena** [comment]
You can try to place your all php version to base dir of `c:/php` and then try to add it again.

**Comment by yCodeTech** [comment]
Valet expects PHP to be in `c:/php`.

From the 

> If you don't have PHP installed, make sure to install it.
> 
> Download the Zip file and unzip into C:/php/.

**Comment by yCodeTech** [comment]
After reviewing the code, I can confirm that the PHP doesn't have to be in `c:/php`. Valet finds the installed PHP via the environment variables, and uses that path. So my previous statement is wrong, apologies.

I'll do some tests tomorrow. But I suspect it can't find the default PHP. But until tests are complete I can't say for sure.

In the meantime, please make sure all old configuration files and folders from cretueusebiu's valet have indeed been deleted.

**Comment by yCodeTech** [comment]
After testing. The command fails because of the space in the path: `Program Files`. A fix is in place, and a patch will be out momentarily as v3.1.2. Please update to this version when its available.
