### ISSUE TITLE
Valet fresh installation issue file_get_content

### ISSUE THREAD

**Issue by hemant-kr-meena** [yCodeTech/valet-windows#3]
![valet-fresh-installation-error](https://github.com/yCodeTech/valet-windows/assets/38046347/14c83a08-04cc-401c-9227-ff5b74821ea1)
On fresh installation of valet. Valet try to get read config.json even it is not yet created and exits.

**Comment by yCodeTech** [comment]
Strange that I've never come across this error before today. Might've been a bug caused by various code changes for the installation. Thanks for the fix.
